### ISSUE TITLE
exercise CSS class is overriding CNX exercise class

### ISSUE THREAD

**Issue by edwoodward** [openstax/concept-coach#32]
The exercise class in concept-coach/assets/main.css has changed the font size of all of the CNX exercises to 1.8em which is larger than expected on our site. Can this class be renamed for Concept Coach? You can see the issue by comparing the 2 links below.

http://dev.cnx.org/contents/GFy_h8cu@9.87:agVo2CPX@12/The-Science-of-Biology

http://cnx.org/contents/185cbf87-c72e-48f5-b51e-f14f21b5eabd@9.87:10/Synthesis-of-Biological-Macrom

**Comment by nathanstitt** [comment]
Looks like it's because we're importing the styles from `openstax/react-components` without enclosing them inside the `.concept-coach` scope at https://github.com/openstax/concept-coach/blob/master/resources/styles/main.less#L1.

We should chat about how we import the styles.  I'd suggest we could perform all the imports inside the .concept-coach selector, unless there's some styles that should be applied outside it?

**Comment by philschatz** [comment]
This should be fixed with #33!
